@startuml

' configuration
hide circle
skinparam linetype ortho

' comment
entity "destination" {
  id: number
  --
  name: varchar2(128)
  hint1: varchar2(256)
  hint2: varchar2(256)
  hint3: varchar2(256) 
  hint4: varchar2(256) 
  hint5: varchar2(256)
}

entity "user" {
  id: number
  --
  password_hash: varchar2(256)
  name: varchar2(128)
  email: varchar2(128)
}

entity "quiz_result" {
  user_id[fk]: number
  destination_id[fk]: number
  --
  hint_difficulty: number
  remaining_guesses: number
  ongoing: boolean
}

@enduml