@startuml

[*] --> WelcomeScreen
WelcomeScreen : InputfieldUsername
WelcomeScreen : InputfieldPassword
WelcomeScreen : ButtonLogin
WelcomeScreen : ButtontTryIt

WelcomeScreen --> WelcomeScreen : Incorrect login
WelcomeScreen --> StatusScreen : ButtonLogin
WelcomeScreen --> StatusScreen : ButtonTryIt
WelcomeScreen --> [*]

StatusScreen : TextfieldQuizStats
StatusScreen : InputfieldRunSpecificQuiz
StatusScreen : ButtonRunSpecificQuiz
StatusScreen : ButtonRunRandomQuiz
StatusScreen : ButtonLogout

StatusScreen --> QuizScreen : ButtonRunSpecificQuiz
StatusScreen --> QuizScreen : ButtonRunRandomQuiz
StatusScreen --> WelcomeScreen : ButtonLogout

QuizScreen : TextfieldHint
QuizScreen : PictureHint
QuizScreen : ButtonAnswer
QuizScreen : ButtonSkipHint

QuizScreen --> QuizScreen : ButtonSkipHint
QuizScreen --> QuizScreen : ButtonAnswer (Incorrect guess)
QuizScreen --> CorrectScreen : ButtonAnswer (Correct guess)
QuizScreen --> FailureScreen : ButtonAnswer (Incorrect guess and no more guesses left)

CorrectScreen : TextfieldNumberOfPoints
CorrectScreen : TextfieldPercentageOfPeopleWhoGotIt
CorrectScreen : ButtonBackToStatus

CorrectScreen --> StatusScreen : ButtonBackToStatus

FailureScreen : TextfieldCorrectAnswer
FailureScreen : ButtonBackToStatus

FailureScreen --> StatusScreen : ButtonBackToStatus
@enduml
